Another monstrous pull.
datawookie/www-exegetic-biz pull request #88
Opened 2019-08-28 07:41 UTC by Axiematic

2019-08-28 08:37 UTC, datawookie requested changes
Hi @Axiematic, this looks pretty good. I see that there's a lot of content added to .../old-training-courses/. I've made a card to clean that up. Also noted a few cases where it would be better to use Hugo shortcodes for links rather than hard-coding the links. Thanks, ABC/

2019-08-28 08:37 UTC, datawookie commented on content/training/docker.md
> +  - The [UNIX Essentials](https://www.exegetic.biz/training/unix-essentials/) course is useful for understanding some of the details of a Dockerfile.
We can use the Hugo shorthand here for creating the link. See [this](https://gohugo.io/content-management/cross-references/).

2019-08-28 08:37 UTC, datawookie commented on content/training/r-machine-learning.md
> +  Participants are assumed to have prior exposure to R, or at least to programming of some variety. Ideally participants should have completed the [Data Wrangling](https://www.exegetic.biz/training/r
Definitely better to use shortcodes here too, please!

2019-08-28 08:37 UTC, datawookie commented on content/training/r-machine-learning-time-series.md
> +  We assume that participants have prior experience with R, ideally having completed both the the [Introduction to R](https://www.exegetic.biz/training/r-introduction/) and [Data Wrangling](https://w
Use shortcodes.

2019-08-28 08:37 UTC, datawookie commented on content/training/r-markdown-automated-reporting.md
> +  - Participants are assumed to have prior exposure to R, or at least to programming of some variety. Ideally participants should have completed the [Data Wrangling](https://www.exegetic.biz/training
Use shortcodes.

2019-08-28 08:37 UTC, datawookie commented on content/training/r-shiny-apps.md
> +  Participants are assumed to have prior exposure to R, or at least to programming of some variety. Ideally participants should have completed the [Data Wrangling](https://www.exegetic.biz/training/r
Use shortcodes.

2019-08-28 08:37 UTC, datawookie commented on content/training/r-visualisation.md
> +  Participants are assumed to have prior experience with R, ideally having completed both the the [Introduction to R](https://www.exegetic.biz/training/r-introduction/) and [Data Wrangling](https://w
Use shortcodes.

2019-09-13 15:06 UTC, datawookie commented
Hi @Axiematic,

Okay, whew! This is huge. I've taken another look and I'm generally happy with this. Some parts of this really need to go live ASAP. But...

1. There are some change requests that have not been dealt with (all relating to using Hugo shortcodes for links rather than hard-coded paths).
2. Let's try not to let this happen again. Rather make a pull request after every feature has been completed. So do something, check that it works/looks good and then immediately create a pull request.

Please let's sort this out ASAP on Tuesday.

Thanks,
Dad.

2019-09-17 09:37 UTC, Axiematic commented
Hi @datawookie 

1. None of the shortcode methods seem to work in the front matter. I've done some extensive Googling and can't seem to find a solution other than just using the original links.

2019-09-17 17:03 UTC, datawookie commented
Ah, shit. How annoying.

Okay, I'm going to merge this. Please check on the site tomorrow morning to ensure that nothing had broken.

And let's keep these PR short and sweet in future.

2019-09-17 17:04 UTC, datawookie approved these changes

2019-09-17 17:11 UTC, merged

2019-09-18 05:37 UTC, Axiematic commented
@datawookie everything looks good to me :).